### ISSUE TITLE
WebGL Canvas can't render without Levels module installed

### ISSUE THREAD

**Issue by Fair-Strides** [erithtotl/FVTT-Wall-Height#18]
I went back through the recent commits to figure out why my controls and scenes weren't rendering and saw a reference to the Levels module. That'd explain the error I keep getting about "_levels is not defined" in patches.js. I assume that's erroring out in a way to stop the entire process from proceeding.

![image](https://user-images.githubusercontent.com/72034470/122632830-1f0de280-d08a-11eb-8e60-5e3e3f6cc03b.png)

**Comment by foxreinhold** [comment]
Having same exact issue.  Breaks Wall height completely for 0.7.10 and prior as they cannot make use of Levels module.

![image](https://user-images.githubusercontent.com/77173822/122633316-fabfff00-d0a5-11eb-99be-c387b226c51f.png)

**Comment by Merudo** [comment]
In the meanwhile, we can downgrade to the 3.5.3.6 version by manually install the following json:

https://raw.githubusercontent.com/erithtotl/FVTT-Wall-Height/3.5.3.6/module.json

**Comment by Tristan-Goucher** [comment]
Ah, I forgot to mention that I'm using 0.8.7. Whoops!

And thanks @Merudo for that idea. I hadn't thought of that, but that is a _very_ useful link if you're running a session soon that needs this. (Thankfully, my party is going into ruins with solid walls tomorrow)

**Comment by theripper93** [comment]
Yes, it's my fault (levels dev here) very sorry for the fuckup - i sent a fix to erithtotl
