### ISSUE TITLE
Very slow token movement when Wall Height is activated

### ISSUE THREAD

**Issue by FatBiscuit** [erithtotl/FVTT-Wall-Height#3]
The features of Wall Height are working fine, but while it's active many PC tokens move especially slow.  In other words, there is a significant lag between when I press the up arrow on my keyboard and when the token actually moves.  If I disable the Wall Height module, token movement goes back to normal.  Any ideas?

**Comment by FatBiscuit** [comment]
Upon further investigation, this problem is exacerbated by token heights above 0.  Tokens at 0 height have only a small amount of movement lag (still more than with the module inactive), but tokens with some height added (10, 20, 30, etc) move with much greater lag.

**Comment by erithtotl** [comment]
This should be fixed.  The issue was with my support for libWrapper for module compatibility.  Wrapping the Foundry method 'testwall' resulted in a massive perf hit due to the frequency in which it is called (10s of thousands of times). 3.5.3.2 the newest release should address this.
