### ISSUE TITLE
Tooltip is unwieldy

### ISSUE THREAD

**Issue by Red5Phil** [erithtotl/FVTT-Wall-Height#5]
The new tooltip is too large and opaque and tends to get in the way when I am trying to fine tune wall positions. I would consider making it smaller and eliminating/reducing the background fill behind the text. An option to toggle the tooltip off would be another change that might help with this issue.

**Comment by erithtotl** [comment]
Hmm, this may have to do with scaling the tooltip, as it is small on the maps I have tested, can you submit a screenshot?

**Comment by Red5Phil** [comment]
From another user on BaileyWiki's forum:

![image](https://user-images.githubusercontent.com/74836493/108243511-ca764d00-7113-11eb-9560-6058bd0b55aa.png)
![image](https://user-images.githubusercontent.com/74836493/108243535-d19d5b00-7113-11eb-9a05-2d154565b188.png)

**Comment by erithtotl** [comment]
> From another user on BaileyWiki's forum:
> 
> ![image](https://user-images.githubusercontent.com/74836493/108243511-ca764d00-7113-11eb-9560-6058bd0b55aa.png)
> ![image](https://user-images.githubusercontent.com/74836493/108243535-d19d5b00-7113-11eb-9a05-2d154565b188.png)

Hi would you be willing to beta test a fix for this? 

.  I think what I have is an improvement but I'd like feedback from someone whose had an issue

**Comment by erithtotl** [comment]
I've reduced the size of the tooltip box, and moved it to be less intrusive.  In addition I added a setting in module settings to disable it.

**Comment by Red5Phil** [comment]
> Hi would you be willing to beta test a fix for this?
> 
> . I think what I have is an improvement but I'd like feedback from someone whose had an issue

Sorry, just now seeing this. The tooltip does still seem to behave a little strangely. Sometimes it will get stuck and doesn't go away until I refresh my browser. The sizing issue still appears to be present as well. I am currently using Forge to host, Foundry versuib 0.7.9, Module Version 3.5.33
