### ISSUE TITLE
Scene-Level Disable Doesn't Disable Height Tooltip

### ISSUE THREAD

**Issue by tjlanza** [erithtotl/FVTT-Wall-Height#9]
FVTT 0.7.9, Wall Height 3.5.3.3

Turning off wall-height at the scene level should prevent the tooltip from showing up, too.

![Disabled w/ Tooltip](https://user-images.githubusercontent.com/21128724/109715548-c31e5d00-7b71-11eb-9cce-0c16748c4677.png)

**Comment by erithtotl** [comment]
This will be fixed in the next release.
